# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' tour_superSimple
NULL

tour_superSimple <- function(n) {
    .Call(`_M2algorithmique_tour_superSimple`, n)
}

#' Insertion sort algorithm using C++
NULL

insertion_sort_Rcpp <- function(v) {
    .Call(`_M2algorithmique_insertion_sort_Rcpp`, v)
}

build_heap_Rcpp <- function(heap, i, n) {
    .Call(`_M2algorithmique_build_heap_Rcpp`, heap, i, n)
}

#' Heap sort algorithm using C++
#'
#' @param v an unsorted vector of numeric data
#' @return a sorted vector
#' @export
heap_sort_Rcpp <- function(v) {
    .Call(`_M2algorithmique_heap_sort_Rcpp`, v)
}

