# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Commerce <- function(type) {
    .Call(`_M2algorithmique_Commerce`, type)
}

compute_distances <- function(data) {
    .Call(`_M2algorithmique_compute_distances`, data)
}

#' Insertion Sort Algorithm (C++ Implementation)
#'
#' @description
#' This function implements the **Insertion Sort** algorithm in C++ and is exported to R using Rcpp. 
#' Insertion Sort is a simple sorting algorithm that builds the sorted sequence one element at a time 
#' by inserting each new element into its correct position within the sorted part of the vector.
#'
#' The algorithm works by iterating through the input vector and shifting larger elements to the right 
#' before inserting the current element (key) into its proper position.
#'
#' @param v A numeric vector containing unsorted elements.
#'
#' @return A numeric vector of the same length as `v`, sorted in ascending order.
#'
#' @details
#' - Time Complexity: **O(n²)** in the worst and average cases, **O(n)** in the best case (already sorted data).
#' - Space Complexity: **O(1)** (in-place sorting, no additional memory used).
#' - Stable Sorting Algorithm: Maintains the relative order of equal elements.
#'
#' @examples
#' insertion_sort_Rcpp(rnorm(100))
#' insertion_sort_Rcpp(sample(100))
#'
#' @export
insertion_sort_Rcpp <- function(v) {
    .Call(`_M2algorithmique_insertion_sort_Rcpp`, v)
}

#' Maintains the heap property by sifting down an element
#'
#' @description
#' This function ensures the **max-heap property** in a given numeric vector. 
#' It is used internally by heap sort to reorganize the vector into a valid max-heap.
#'
#' @param heap A numeric vector representing a heap.
#' @param i The index of the current element to heapify (1-based indexing).
#' @param n The number of elements in the heap.
#' @return The modified heap with the max-heap property restored.
#' @note This function modifies the input vector in-place.
#'
#' @keywords internal
NULL

#' Heap Sort Algorithm (C++ Implementation)
#'
#' @description
#' This function implements **Heap Sort**, an efficient sorting algorithm that 
#' first builds a max-heap and then repeatedly extracts the maximum element to 
#' produce a sorted sequence.
#'
#' The algorithm consists of two main steps:
#' \enumerate{
#'   \item \bold{Heap Construction:} The input vector is reorganized into a max-heap.
#'   \item \bold{Sorting:} The largest element (root) is swapped with the last element, 
#'     reducing the heap size and reapplying heapify.
#' }
#'
#' @param v A numeric vector containing unsorted elements.
#' @return A numeric vector sorted in ascending order.
#'
#' @details
#' \itemize{
#'   \item \bold{Time Complexity:}
#'     \itemize{
#'       \item Building the heap: O(n)
#'       \item Extracting elements: O(n log n)
#'       \item Overall: O(n log n)
#'     }
#'   \item \bold{Space Complexity:} O(1) (in-place sorting).
#'   \item \bold{Unstable Sort:} The relative order of equal elements may change.
#' }
#' @examples
#' heap_sort_Rcpp(rnorm(100))
#' heap_sort_Rcpp(sample(100))
#'
#' @export
heap_sort_Rcpp <- function(v) {
    .Call(`_M2algorithmique_heap_sort_Rcpp`, v)
}

